#This program takes a valid bf file input and converts it into a file which when run by CPU-8 will interpret the file as brainfuck

def bf_filter(text_file_object):
	'''removes comments from a bf file'''
	bf = []
	valid_symbols = {
					"+":43,
					"-":45,
					"<":60,
					">":62,
					"[":91,
					"]":93,
					".":46}
	for line in text_file_object:
		for character in line:
			try:
				bf.append(valid_symbols[character])
			except:
				break #ends line
	return bf

def create_data_text(brainfuck):
	text = '''
	#This code was generated by the brainfuck compiler

	import brainf_ck:all

	%%instructions '''
	for command in brainfuck:
		text = text + "data " + str(command) + "\n"
	return text




